SIM ?= ghdl
TOPLEVEL_LANG ?= vhdl

VHDL_SOURCES += ${DUT}.vhdl

SIM_ARGS = --vcd=waves.vcd	# Solo para VHDL. En verilog el .vcd se renombra desde el source file.

# TOPLEVEL es el nombre del módulo toplevel (el de los puertos) en tu archivo HDL.
TOPLEVEL := ${DUT}

# MODULE is the basename of the Python test file
MODULE := test_${DUT}

# Incluya las reglas de make que utiliza cocotb para configurar el simulador
include \$(shell cocotb-config --makefiles)/Makefile.sim
