name: CoresTestLocal #Nombre del workflow

on: 
  push:
    branches:
      - main 
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs: #Son los trabajos que realizará, en este caso de forma secuencial
  Test:
    runs-on: ubuntu-latest #OS que usará la vm de github para correr el workflow
    steps: #pasos del workflow
    - uses: actions/checkout@v4 # Descarga la última versión del código

    - name: Docker Login
      run: docker login --username utn-ba-sats --password ${{ secrets.GITHUB_TOKEN }} ghrc.io

    - name: Build Docker Image
      run: docker build -t my-docker-image -f ./Dockerfile .

    - name: Run Docker Tests
      run: docker run --rm my-docker-image ./run_tests_pipeline.sh

 
