name: CoresTest #Nombre del workflow

on:
  push:  #Accion con la que se activa, en la lista de brunchs
    branches:  
      - main

jobs: #Son los trabajos que realizara, en este caso de forma secuencial
  Test:
    runs-on: ubuntu-latest #OS que usará la vm de github para correr el workflow
    steps: #pasos del workflow
    - uses: actions/checkout@v4 #Es una accion propia de actions, lo que hace es traer la ultima version de tu rama

    - name: Docker Login
      run: docker login --username utn-ba-sats --password ${{ secrets.GITHUB_TOKEN }} ghrc.io
    
    - name: Build Image #Nombre de este step
      run: make build-docker #Comando que va a ejecutar

   # - name: Run Dynamic Tests
   #   run: python3 .github/scripts/run_dynamic_tests.py
    
    
    - name: Test cores
      run: make test
     